/*
 * Timer0.c
 *
 * Created: 6/26/2025 6:47:37 AM
 *  Author: ibrah
 */ 

#include "Timer0.h"
#include "Timer0_register.h"
#include "../Interrupt/GIE_INTERFACE.h"
#include "Timer0_config.h"
#include "Timer0_private.h"


static void (*TIMER0_overflow_ISR_ptr)(void);
static void (*TIMER0_compare_ISR_ptr)(void);

STD_RETURN_TYPE TIMER0_confiG_file_init()
{
	/***TIMER0****/
	STD_RETURN_TYPE ret=E_OK;
	#if TIMER0_STATE==TIMER0_ENABLED
	
	#if (TIMER0_VALIDATE_WAVEFORM_MODE(TIMER0_WAVEFORM_MODE))&&(TIMER0_VALIDATE_CLOCK_SOURCE(TIMER0_CLOCK_SOURCE))
	#if TIMER0_WAVEFORM_MODE==TIMER0_WAVEFORM_MODE_NORMAL
	
	#if TIMER0_VALIDATE_NON_PWM_COMPARE_MODE(TIMER0_COMPARE_MODE)
	TIMER0_SELECT_WAVEFROM_MODE(TIMER0_WAVEFORM_MODE_NORMAL);
	TIMER0_SELECT_COMPARE_MODE(TIMER0_COMPARE_MODE);
	TIMER0_SELECT_CLOCK_SOURCE(TIMER0_CLOCK_SOURCE);
	
	#if TIMER0_INTERRUPT_COMPARE_STATE==TIMER0_COMPARE_INTERRUPT_ENABLED
	TIMER0_INTERRUPT_COMPARE_ENABLE();
	GIE_ENABLE();
	#elif TIMER0_INTERRUPT_COMPARE_STATE==TIMER0_COMPARE_INTERRUPT_DISABLED
	TIMER0_INTERRUPT_COMPARE_DISABLE();
	#else
	ret=E_NOK;
	#endif
	
	#if TIMER0_INTERRUPT_OVERFLOW_STATE==TIMER0_OVERFLOW_INTERRUPT_ENABLED
	TIMER0_INTERRUPT_OVERFLOW_ENABLE();
	GIE_ENABLE();
	#elif TIMER0_INTERRUPT_OVERFLOW_STATE==TIMER0_OVERFLOW_INTERRUPT_DISABLED
	TIMER0_INTERRUPT_OVERFLOW_DISABLE();
	#else
	ret=E_NOK;
	#endif
	
	#else
	ret=E_NOK;
	#endif
	
	
	#elif TIMER0_WAVEFORM_MODE==TIMER0_WAVEFORM_MODE_CTC
	TIMER0_SELECT_WAVEFROM_MODE(TIMER0_WAVEFORM_MODE_CTC);
	#if TIMER0_VALIDATE_NON_PWM_COMPARE_MODE(TIMER0_COMPARE_MODE)
	TIMER0_SELECT_COMPARE_MODE(TIMER0_COMPARE_MODE);
	TIMER0_SELECT_CLOCK_SOURCE(TIMER0_CLOCK_SOURCE);
	
	#if TIMER0_INTERRUPT_COMPARE_STATE==TIMER0_COMPARE_INTERRUPT_ENABLED
	TIMER0_INTERRUPT_COMPARE_ENABLE();
	GIE_ENABLE();
	#elif TIMER0_INTERRUPT_COMPARE_STATE==TIMER0_COMPARE_INTERRUPT_DISABLED
	TIMER0_INTERRUPT_COMPARE_DISABLE();
	#else ret=E_NOK;
	#endif
	
	#if TIMER0_INTERRUPT_OVERFLOW_STATE==TIMER0_OVERFLOW_INTERRUPT_ENABLED
	TIMER0_INTERRUPT_OVERFLOW_ENABLE();
	GIE_ENABLE();
	#elif TIMER0_INTERRUPT_OVERFLOW_STATE==TIMER0_OVERFLOW_INTERRUPT_DISABLED
	TIMER0_INTERRUPT_OVERFLOW_DISABLE();
	#else
	ret=E_NOK;
	#endif
	
	#else
	ret=E_NOK;
	#endif
	
	#elif TIMER0_WAVEFORM_MODE==TIMER0_WAVEFORM_MODE_FAST_PWM
	
	#if TIMER0_VALIDATE_PWM_COMPARE_MODE(TIMER0_COMPARE_MODE)
	TIMER0_SELECT_WAVEFROM_MODE(TIMER0_WAVEFORM_MODE_FAST_PWM);
	TIMER0_SELECT_COMPARE_MODE(TIMER0_COMPARE_MODE);
	TIMER0_SELECT_CLOCK_SOURCE(TIMER0_CLOCK_SOURCE);
	
	#if TIMER0_INTERRUPT_COMPARE_STATE==TIMER0_COMPARE_INTERRUPT_ENABLED
	TIMER0_INTERRUPT_COMPARE_ENABLE();
	GIE_ENABLE();
	#elif TIMER0_INTERRUPT_COMPARE_STATE==TIMER0_COMPARE_INTERRUPT_DISABLED
	TIMER0_INTERRUPT_COMPARE_DISABLE();
	#else
	ret=E_NOK;
	#endif
	
	#if TIMER0_INTERRUPT_OVERFLOW_STATE==TIMER0_OVERFLOW_INTERRUPT_ENABLED
	TIMER0_INTERRUPT_OVERFLOW_ENABLE();
	GIE_ENABLE();
	#elif TIMER0_INTERRUPT_OVERFLOW_STATE==TIMER0_OVERFLOW_INTERRUPT_DISABLED
	TIMER0_INTERRUPT_OVERFLOW_DISABLE();
	#else
	ret=E_NOK;
	#endif
	
	#else
	ret=E_NOK;
	#endif
	
	#elif TIMER0_SELECT_WAVEFROM_MODE==TIMER0_WAVEFORM_MODE_PWM_PHASE_CORRECT
	
	#if TIMER0_VALIDATE_PWM_PHASE_CORRECT_COMPARE_MODE(TIMER0_COMPARE_MODE)
	TIMER0_SELECT_WAVEFROM_MODE(TIMER0_WAVEFORM_MODE_PWM_PHASE_CORRECT);
	TIMER0_SELECT_COMPARE_MODE(TIMER0_COMPARE_MODE);
	TIMER0_SELECT_CLOCK_SOURCE(TIMER0_CLOCK_SOURCE);
	
	#if TIMER0_INTERRUPT_COMPARE_STATE==TIMER0_COMPARE_INTERRUPT_ENABLED
	TIMER0_INTERRUPT_COMPARE_ENABLE();
	GIE_ENABLE();
	#elif TIMER0_INTERRUPT_COMPARE_STATE==TIMER0_COMPARE_INTERRUPT_DISABLED
	TIMER0_INTERRUPT_COMPARE_DISABLE();
	#else ret=E_NOK;
	#endif
	
	#if TIMER0_INTERRUPT_OVERFLOW_STATE==TIMER0_OVERFLOW_INTERRUPT_ENABLED
	TIMER0_INTERRUPT_OVERFLOW_ENABLE();
	GIE_ENABLE();
	#elif TIMER0_INTERRUPT_OVERFLOW_STATE==TIMER0_OVERFLOW_INTERRUPT_DISABLED
	TIMER0_INTERRUPT_OVERFLOW_DISABLE();
	#else
	ret=E_NOK;
	#endif
	
	#else
	ret=E_NOK;
	#endif
	
	#else
	ret=E_NOK;
	
	#endif
	#else
	ret=E_NOK
	#endif
	
	#elif TIMER0_STATE==TIMER0_DISABLED
	TIMER0_DISABLE();
	#endif
	/*TIMER0**/
	
	
	/*TIMER1*/
	
	
	
	
	/*TIMER1*/
	
	return ret;
}

STD_RETURN_TYPE TIMER0_disable()
{
	STD_RETURN_TYPE ret=E_OK;
	TIMER0_DISABLE();
	
	return ret;
}
STD_RETURN_TYPE TIMER0_send_overflow_isr(void (*ISR_ptr)(void))
{
	STD_RETURN_TYPE ret=E_OK;
	if(NULL==ISR_ptr)
	{
		ret=E_NOK;
	}
	else
	{
		TIMER0_overflow_ISR_ptr=ISR_ptr;
	}
	
	return ret;
}
STD_RETURN_TYPE TIMER0_send_compare_match_isr(void (*ISR_ptr)(void))
{
	STD_RETURN_TYPE ret=E_OK;
	if(NULL==ISR_ptr)
	{
		ret=E_NOK;
	}
	else
	{
		TIMER0_compare_ISR_ptr=ISR_ptr;
	}
	return ret;
}


STD_RETURN_TYPE TIMER0_set_compare_value(uint8 compare_value)
{
	STD_RETURN_TYPE ret=E_OK;
	TIMER0_WRITE_COMPARE_VALUE(compare_value);
	return ret;
}

STD_RETURN_TYPE TIMER0_write_value(uint8 value)
{
	STD_RETURN_TYPE ret=E_OK;
	TIMER0_WRITE_VALUE(value);
	return ret;
}
STD_RETURN_TYPE TIMER0_set_duty_cycle(uint8 duty_cycle)
{
	STD_RETURN_TYPE ret=E_OK;
	#if TIMER0_COMPARE_MODE==TIMER0_COMPARE_OUTPUT_PWM_CLEAR_ON_COMPARE_SET_ON_TOP
	TIMER0_WRITE_COMPARE_VALUE((uint8)(255*((float)duty_cycle/100.00)));
	#elif TIMER0_COMPARE_MODE==TIMER0_COMPARE_OUTPUT_PWM_SET_ON_COMPARE_CLEAR_ON_TOP
	TIMER0_WRITE_COMPARE_VALUE((uint8)((1-((float)duty_cycle/100.00))*255));
	#else
	ret=E_NOK;
	#endif
	
	
	return ret;
}

__attribute__((signal)) void __vector_11(void)
{
	if(TIMER0_compare_ISR_ptr)
	{
		TIMER0_compare_ISR_ptr();
	}
	TIMER0_INTERRUPT_COMPARE_CLEAR_FLAG();
}

__attribute__((signal)) void __vector_12(void)
{
	if(TIMER0_overflow_ISR_ptr)
	{
		TIMER0_overflow_ISR_ptr();
	}
	TIMER0_INTERRUPT_OVERFLOW_CLEAR_FLAG();
}