/*
 * Timer0_private.h
 *
 * Created: 6/26/2025 6:47:27 AM
 *  Author: ibrah
 */ 


#ifndef TIMER0_PRIVATE_H_
#define TIMER0_PRIVATE_H_

/***************Section:includes***************/
#include "Timer0_register.h"
/***************Section:macro definitions***************/

#define TIMERS_DRIVER_CONFIG_ENABLED	1
#define TIMERS_DRIVER_CONFIG_DISABLED	0
/*TIMER0 state*/
#define TIMER0_ENABLED		1
#define TIMER0_DISABLED		0
/*TIMER0 waveform modes*/
#define TIMER0_WAVEFORM_MODE_NORMAL				0
#define TIMER0_WAVEFORM_MODE_PWM_PHASE_CORRECT	1
#define TIMER0_WAVEFORM_MODE_CTC				2
#define TIMER0_WAVEFORM_MODE_FAST_PWM			3

/*TIMER0 COMPARE modes*/
#define TIMER0_COMPARE_OUTPUT_NON_PWM_NORMAL				0
#define TIMER0_COMPARE_OUTPUT_NON_PWM_TOGGLE_ON_COMPARE		1
#define TIMER0_COMPARE_OUTPUT_NON_PWM_CLEAR_ON_COMPARE		2
#define TIMER0_COMPARE_OUTPUT_NON_PWM_SET_OC0_ON_COMPARE	3

#define TIMER0_COMPARE_OUTPUT_PWM_NORMAL							0
#define TIMER0_COMPARE_OUTPUT_PWM_CLEAR_ON_COMPARE_SET_ON_TOP		2
#define TIMER0_COMPARE_OUTPUT_PWM_SET_ON_COMPARE_CLEAR_ON_TOP		3

#define TIMER0_COMPARE_OUTPUT_PHASE_PWM_NORMAL														0
#define TIMER0_COMPARE_OUTPUT_PHASE_PWM_CLEAR_ON_COMPARE_UP_COUNTING_SET_ON_COMPARE_DOWN_COUNTING	2
#define TIMER0_COMPARE_OUTPUT_PHASE_PWM_SET_ON_COMPARE_UP_COUNTING_CLEAR_ON_COMPARE_DOWN_COUNTING	3

/*TIMER0 clock source*/
#define TIMER0_NO_CLOCK_SOURCE			0
#define TIMER0_PRESCALER_DIV_1			1
#define TIMER0_PRESCALER_DIV_8			2
#define TIMER0_PRESCALER_DIV_64			3
#define TIMER0_PRESCALER_DIV_256		4
#define TIMER0_PRESCALER_DIV_1024		5
#define TIMER0_EXTERNAL_FALLING_EDGE	6
#define TIMER0_EXTERNAL_RISING_EDGE		7

/*TIMER0 interrupt*/
#define TIMER0_OVERFLOW_INTERRUPT_ENABLED	1
#define TIMER0_OVERFLOW_INTERRUPT_DISABLED	0

#define TIMER0_COMPARE_INTERRUPT_ENABLED		1
#define TIMER0_COMPARE_INTERRUPT_DISABLED		0

/*definitions for readability*/

#define MAX_DUTY_CYCLE 100

/***************Section:function like macro***************/
#define TIMER0_DISABLE()	(TCCR0->TCCR0_BITS.CS0=0)

#define TIMER0_VALIDATE_WAVEFORM_MODE(MODE)	((TIMER0_WAVEFORM_MODE_NORMAL==MODE)||(TIMER0_WAVEFORM_MODE_FAST_PWM==MODE)||(TIMER0_WAVEFORM_MODE_CTC==MODE)||(TIMER0_WAVEFORM_MODE_PWM_PHASE_CORRECT==MODE))
#define TIMER0_SELECT_WAVEFROM_MODE(MODE)	do \
{ \
	TCCR0->TCCR0_BITS.WGM00=GET_BIT(MODE,0); \
	TCCR0->TCCR0_BITS.WGM01=GET_BIT(MODE,1); \
}while(0);

#define TIMER0_VALIDATE_CLOCK_SOURCE(CLOCK_SOURCE)	((TIMER0_NO_CLOCK_SOURCE<=CLOCK_SOURCE)&&(TIMER0_EXTERNAL_RISING_EDGE>=CLOCK_SOURCE))
#define TIMER0_SELECT_CLOCK_SOURCE(CLOCK_SOURCE)	(TCCR0->TCCR0_BITS.CS0=CLOCK_SOURCE)

#define TIMER0_VALIDATE_NON_PWM_COMPARE_MODE(COMPARE_MODE)	((TIMER0_COMPARE_OUTPUT_NON_PWM_NORMAL<=COMPARE_MODE)&&(COMPARE_MODE<=TIMER0_COMPARE_OUTPUT_NON_PWM_SET_OC0_ON_COMPARE))
#define TIMER0_VALIDATE_PWM_COMPARE_MODE(COMPARE_MODE)		((COMPARE_MODE==TIMER0_COMPARE_OUTPUT_PWM_NORMAL)||(COMPARE_MODE==TIMER0_COMPARE_OUTPUT_PWM_CLEAR_ON_COMPARE_SET_ON_TOP)||(COMPARE_MODE==TIMER0_COMPARE_OUTPUT_PWM_SET_ON_COMPARE_CLEAR_ON_TOP))
#define TIMER0_VALIDATE_PWM_PHASE_CORRECT_COMPARE_MODE(COMPARE_MODE)	((TIMER0_COMPARE_OUTPUT_PHASE_PWM_NORMAL==COMPARE_MODE)||(TIMER0_COMPARE_OUTPUT_PHASE_PWM_CLEAR_ON_COMPARE_UP_COUNTING_SET_ON_COMPARE_DOWN_COUNTING==COMPARE_MODE)||(TIMER0_COMPARE_OUTPUT_PHASE_PWM_SET_ON_COMPARE_UP_COUNTING_CLEAR_ON_COMPARE_DOWN_COUNTING==COMPARE_MODE))


#define TIMER0_SELECT_COMPARE_MODE(MODE)			(TCCR0->TCCR0_BITS.COM0=MODE)

#define TIMER0_WRITE_COMPARE_VALUE(COMPARE_VALUE)	(OCR0=COMPARE_VALUE)
#define TIMER0_WRITE_VALUE(VALUE)					(TCNT0=VALUE)

#define TIMER0_INTERRUPT_OVERFLOW_ENABLE()			(TIMSK->TIMSK_BITS.TOIE0=TIMER0_OVERFLOW_INTERRUPT_ENABLED)
#define TIMER0_INTERRUPT_OVERFLOW_DISABLE()			(TIMSK->TIMSK_BITS.TOIE0=TIMER0_OVERFLOW_INTERRUPT_DISABLED)

#define TIMER0_INTERRUPT_COMPARE_ENABLE()			(TIMSK->TIMSK_BITS.OCIE0=TIMER0_COMPARE_INTERRUPT_ENABLED)
#define TIMER0_INTERRUPT_COMPARE_DISABLE()			(TIMSK->TIMSK_BITS.OCIE0=TIMER0_COMPARE_INTERRUPT_DISABLED)

#define TIMER0_INTERRUPT_OVERFLOW_CLEAR_FLAG()		(TIFR->TIFR_BITS.TOV0=1)
#define TIMER0_INTERRUPT_COMPARE_CLEAR_FLAG()		(TIFR->TIFR_BITS.OCF0=1)

/***************Section:type definitions***************/


/***************Section:function decleratoins***************/




#endif /* TIMER0_PRIVATE_H_ */