/*
 * Timer0_config.h
 *
 * Created: 6/26/2025 6:47:16 AM
 *  Author: ibrah
 */ 


#ifndef TIMER0_CONFIG_H_
#define TIMER0_CONFIG_H_

/***************Section:includes***************/
#include "Timer0_private.h"
/***************Section:macro definitions***************/

/*
TIMERS_DRIVER_CONFIG_ENABLED
TIMERS_DRIVER_CONFIG_DISABLED
*/
#define TIMERS_RUN_TIME_CONFIG		TIMERS_DRIVER_CONFIG_ENABLED
#define TIMERS_PREBUILD_CONFIG		TIMERS_DRIVER_CONFIG_ENABLED
/*TIMER0*/

/*
TIMER0_ENABLED
TIMER0_DISABLED
*/
#define TIMER0_STATE	TIMER0_ENABLED

/*TIMER0 waveform modes*/
/*
TIMER0_WAVEFORM_MODE_NORMAL
TIMER0_WAVEFORM_MODE_PWM_PHASE_CORRECT
TIMER0_WAVEFORM_MODE_CTC
TIMER0_WAVEFORM_MODE_FAST_PWM
*/
#define TIMER0_WAVEFORM_MODE	TIMER0_WAVEFORM_MODE_FAST_PWM

/*TIMER0 COMPARE modes*/
/*
TIMER0_COMPARE_OUTPUT_NON_PWM_NORMAL
TIMER0_COMPARE_OUTPUT_NON_PWM_TOGGLE_ON_COMPARE
TIMER0_COMPARE_OUTPUT_NON_PWM_CLEAR_ON_COMPARE
TIMER0_COMPARE_OUTPUT_NON_PWM_SET_OC0_ON_COMPARE

TIMER0_COMPARE_OUTPUT_PWM_NORMAL
TIMER0_COMPARE_OUTPUT_PWM_CLEAR_ON_COMPARE_SET_ON_TOP
TIMER0_COMPARE_OUTPUT_PWM_SET_ON_COMPARE_CLEAR_ON_TOP

TIMER0_COMPARE_OUTPUT_PHASE_PWM_NORMAL
TIMER0_COMPARE_OUTPUT_PHASE_PWM_CLEAR_ON_COMPARE_UP_COUNTING_SET_ON_COMPARE_DOWN_COUNTING
TIMER0_COMPARE_OUTPUT_PHASE_PWM_SET_ON_COMPARE_UP_COUNTING_CLEAR_ON_COMPARE_DOWN_COUNTING
*/
#define TIMER0_COMPARE_MODE	TIMER0_COMPARE_OUTPUT_PWM_CLEAR_ON_COMPARE_SET_ON_TOP


/*TIMER0 clock source*/
/*
TIMER0_NO_CLOCK_SOURCE
TIMER0_PRESCALER_DIV_1
TIMER0_PRESCALER_DIV_8
TIMER0_PRESCALER_DIV_64
TIMER0_PRESCALER_DIV_256
TIMER0_PRESCALER_DIV_1024
TIMER0_EXTERNAL_FALLING_EDGE
TIMER0_EXTERNAL_RISING_EDGE
*/
#define TIMER0_CLOCK_SOURCE		TIMER0_PRESCALER_DIV_8

/*TIMER0 interrupt*/
/*
TIMER0_OVERFLOW_INTERRUPT_ENABLED
TIMER0_OVERFLOW_INTERRUPT_DISABLED
*/
#define TIMER0_INTERRUPT_OVERFLOW_STATE		TIMER0_OVERFLOW_INTERRUPT_ENABLED

/*
TIMER0_COMPARE_INTERRUPT_ENABLED
TIMER0_COMPARE_INTERRUPT_DISABLED
*/
#define TIMER0_INTERRUPT_COMPARE_STATE		TIMER0_COMPARE_INTERRUPT_ENABLED

/***************Section:function like macro***************/


/***************Section:type definitions***************/


/***************Section:function decleratoins***************/



#endif /* TIMER0_CONFIG_H_ */