/*
 * Timer2_private.h
 *
 * Created: 6/26/2025 2:27:30 PM
 *  Author: ibrah
 */ 


#ifndef TIMER2_PRIVATE_H_
#define TIMER2_PRIVATE_H_

/***************Section:includes***************/
#include "../Timer0/Timer0_register.h"
#include "Timer2_register.h"
/***************Section:macro definitions***************/
/*TIMER2 state*/
#define TIMER2_ENABLED		1
#define TIMER2_DISABLED		0
/*TIMER0 waveform modes*/
#define TIMER2_WAVEFORM_MODE_NORMAL				0
#define TIMER2_WAVEFORM_MODE_CTC				2
#define TIMER2_WAVEFORM_MODE_FAST_PWM			3

/*TIMER0 COMPARE modes*/
#define TIMER2_COMPARE_OUTPUT_NON_PWM_NORMAL				0
#define TIMER2_COMPARE_OUTPUT_NON_PWM_CLEAR_ON_COMPARE		2
#define TIMER2_COMPARE_OUTPUT_NON_PWM_SET_OC2_ON_COMPARE	3

#define TIMER2_COMPARE_OUTPUT_PWM_NORMAL							0
#define TIMER2_COMPARE_OUTPUT_PWM_CLEAR_ON_COMPARE_SET_ON_TOP		2
#define TIMER2_COMPARE_OUTPUT_PWM_SET_ON_COMPARE_CLEAR_ON_TOP		3

#define TIMER2_COMPARE_OUTPUT_PHASE_PWM_NORMAL														0
#define TIMER2_COMPARE_OUTPUT_PHASE_PWM_CLEAR_ON_COMPARE_UP_COUNTING_SET_ON_COMPARE_DOWN_COUNTING	2
#define TIMER2_COMPARE_OUTPUT_PHASE_PWM_SET_ON_COMPARE_UP_COUNTING_CLEAR_ON_COMPARE_DOWN_COUNTING	3

/*TIMER0 clock source*/
#define TIMER2_NO_CLOCK_SOURCE			0
#define TIMER2_PRESCALER_DIV_1			1
#define TIMER2_PRESCALER_DIV_8			2
#define TIMER2_PRESCALER_DIV_32			3
#define TIMER2_PRESCALER_DIV_64			4
#define TIMER2_PRESCALER_DIV_128		5
#define TIMER2_PRESCALER_DIV_256		6
#define TIMER2_PRESCALER_DIV_1024		7


/*TIMER0 interrupt*/
#define TIMER2_OVERFLOW_INTERRUPT_ENABLED	1
#define TIMER2_OVERFLOW_INTERRUPT_DISABLED	0

#define TIMER2_COMPARE_INTERRUPT_ENABLED		1
#define TIMER2_COMPARE_INTERRUPT_DISABLED		0
/***************Section:function like macro***************/
#define TIMER2_DISABLE()	(TCCR2->TCCR2_BITS.CS2=0)

#define TIMER2_VALIDATE_WAVEFORM_MODE(MODE)	((TIMER2_WAVEFORM_MODE_NORMAL==MODE)||(TIMER2_WAVEFORM_MODE_FAST_PWM==MODE)||(TIMER2_WAVEFORM_MODE_CTC==MODE))
#define TIMER2_SELECT_WAVEFROM_MODE(MODE)	do \
{ \
	TCCR2->TCCR2_BITS.WGM20=GET_BIT(MODE,0); \
	TCCR2->TCCR2_BITS.WGM21=GET_BIT(MODE,1); \
}while(0);
#define TIMER2_VALIDATE_CLOCK_SOURCE(CLOCK_SOURCE)	((TIMER2_NO_CLOCK_SOURCE<=CLOCK_SOURCE)&&(TIMER2_PRESCALER_DIV_1024>=CLOCK_SOURCE))
#define TIMER2_SELECT_CLOCK_SOURCE(CLOCK_SOURCE)	(TCCR2->TCCR2_BITS.CS2=CLOCK_SOURCE)

#define TIMER2_VALIDATE_NON_PWM_COMPARE_MODE(COMPARE_MODE)	((TIMER2_COMPARE_OUTPUT_NON_PWM_NORMAL<=COMPARE_MODE)&&(COMPARE_MODE<=TIMER2_COMPARE_OUTPUT_NON_PWM_SET_OC2_ON_COMPARE))
#define TIMER2_VALIDATE_PWM_COMPARE_MODE(COMPARE_MODE)		((COMPARE_MODE==TIMER2_COMPARE_OUTPUT_PWM_NORMAL)||(COMPARE_MODE==TIMER2_COMPARE_OUTPUT_PWM_CLEAR_ON_COMPARE_SET_ON_TOP)||(COMPARE_MODE==TIMER2_COMPARE_OUTPUT_PWM_SET_ON_COMPARE_CLEAR_ON_TOP))
#define TIMER2_VALIDATE_PWM_PHASE_CORRECT_COMPARE_MODE(COMPARE_MODE)	((TIMER2_COMPARE_OUTPUT_PHASE_PWM_NORMAL==COMPARE_MODE)||(TIMER2_COMPARE_OUTPUT_PHASE_PWM_CLEAR_ON_COMPARE_UP_COUNTING_SET_ON_COMPARE_DOWN_COUNTING==COMPARE_MODE)||(TIMER2_COMPARE_OUTPUT_PHASE_PWM_SET_ON_COMPARE_UP_COUNTING_CLEAR_ON_COMPARE_DOWN_COUNTING==COMPARE_MODE))


#define TIMER2_SELECT_COMPARE_MODE(MODE)			(TCCR2->TCCR2_BITS.COM2=MODE)

#define TIMER2_WRITE_COMPARE_VALUE(COMPARE_VALUE)	(OCR2=COMPARE_VALUE)
#define TIMER2_WRITE_VALUE(VALUE)					(TCNT2=VALUE)

#define TIMER2_INTERRUPT_OVERFLOW_ENABLE()			(TIMSK->TIMSK_BITS.TOIE2=TIMER2_OVERFLOW_INTERRUPT_ENABLED)
#define TIMER2_INTERRUPT_OVERFLOW_DISABLE()			(TIMSK->TIMSK_BITS.TOIE2=TIMER2_OVERFLOW_INTERRUPT_DISABLED)

#define TIMER2_INTERRUPT_COMPARE_ENABLE()			(TIMSK->TIMSK_BITS.OCIE2=TIMER2_COMPARE_INTERRUPT_ENABLED)
#define TIMER2_INTERRUPT_COMPARE_DISABLE()			(TIMSK->TIMSK_BITS.OCIE2=TIMER2_COMPARE_INTERRUPT_DISABLED)

#define TIMER2_INTERRUPT_OVERFLOW_CLEAR_FLAG()		(TIFR->TIFR_BITS.TOV2=1)
#define TIMER2_INTERRUPT_COMPARE_CLEAR_FLAG()		(TIFR->TIFR_BITS.OCF2=1)


/***************Section:type definitions***************/


/***************Section:function decleratoins**************/



#endif /* TIMER2_PRIVATE_H_ */