/*
 * Timer2_config.h
 *
 * Created: 6/26/2025 2:27:18 PM
 *  Author: ibrah
 */ 


#ifndef TIMER2_CONFIG_H_
#define TIMER2_CONFIG_H_

/***************Section:includes***************/
#include "Timer2_private.h"


/***************Section:macro definitions***************/
/*
TIMER2_ENABLED
TIMER2_DISABLED
*/
#define TIMER2_STATE	TIMER2_ENABLED

/*TIMER0 waveform modes*/
/*
TIMER2_WAVEFORM_MODE_NORMAL
TIMER2_WAVEFORM_MODE_CTC
TIMER2_WAVEFORM_MODE_FAST_PWM
*/
#define TIMER2_WAVEFORM_MODE	TIMER2_WAVEFORM_MODE_FAST_PWM

/*TIMER0 COMPARE modes*/
/*
TIMER2_COMPARE_OUTPUT_NON_PWM_NORMAL
TIMER2_COMPARE_OUTPUT_NON_PWM_CLEAR_ON_COMPARE
TIMER2_COMPARE_OUTPUT_NON_PWM_SET_OC2_ON_COMPARE

TIMER2_COMPARE_OUTPUT_PWM_NORMAL
TIMER2_COMPARE_OUTPUT_PWM_CLEAR_ON_COMPARE_SET_ON_TOP
TIMER2_COMPARE_OUTPUT_PWM_SET_ON_COMPARE_CLEAR_ON_TOP


*/
#define TIMER2_COMPARE_MODE	TIMER2_COMPARE_OUTPUT_PWM_CLEAR_ON_COMPARE_SET_ON_TOP


/*TIMER0 clock source*/
/*
TIMER2_NO_CLOCK_SOURCE			
TIMER2_PRESCALER_DIV_1			
TIMER2_PRESCALER_DIV_8			
TIMER2_PRESCALER_DIV_32			
TIMER2_PRESCALER_DIV_64			
TIMER2_PRESCALER_DIV_128		
TIMER2_PRESCALER_DIV_256		
TIMER2_PRESCALER_DIV_1024		
*/
#define TIMER2_CLOCK_SOURCE		TIMER2_PRESCALER_DIV_8

/*TIMER0 interrupt*/
/*
TIMER2_OVERFLOW_INTERRUPT_ENABLED
TIMER2_OVERFLOW_INTERRUPT_DISABLED
*/
#define TIMER2_INTERRUPT_OVERFLOW_STATE		TIMER2_OVERFLOW_INTERRUPT_ENABLED

/*
TIMER2_COMPARE_INTERRUPT_ENABLED
TIMER2_COMPARE_INTERRUPT_DISABLED
*/
#define TIMER2_INTERRUPT_COMPARE_STATE		TIMER2_COMPARE_INTERRUPT_ENABLED
/***************Section:function like macro***************/



/***************Section:type definitions***************/


/***************Section:function decleratoins**************/



#endif /* TIMER2_CONFIG_H_ */