/*
 * Timer2.c
 *
 * Created: 6/26/2025 2:27:55 PM
 *  Author: ibrah
 */ 

 
#include "Timer2.h"
#include "../Interrupt/GIE_INTERFACE.h"
#include "Timer2_config.h"
#include "Timer2_register.h"


static void (*TIMER2_overflow_ISR_ptr)(void);
static void (*TIMER2_compare_ISR_ptr)(void);

STD_RETURN_TYPE TIMER2_confiG_file_init()
{
	/***TIMER2****/
	STD_RETURN_TYPE ret=E_OK;
	#if TIMER2_STATE==TIMER2_ENABLED
	
	#if (TIMER2_VALIDATE_WAVEFORM_MODE(TIMER2_WAVEFORM_MODE))&&(TIMER2_VALIDATE_CLOCK_SOURCE(TIMER2_CLOCK_SOURCE))
	#if TIMER2_WAVEFORM_MODE==TIMER2_WAVEFORM_MODE_NORMAL
	
	#if TIMER2_VALIDATE_NON_PWM_COMPARE_MODE(TIMER2_COMPARE_MODE)
	TIMER2_SELECT_WAVEFROM_MODE(TIMER0_WAVEFORM_MODE_NORMAL);
	TIMER2_SELECT_COMPARE_MODE(TIMER2_COMPARE_MODE);
	TIMER2_SELECT_CLOCK_SOURCE(TIMER2_CLOCK_SOURCE);
	
	#if TIMER2_INTERRUPT_COMPARE_STATE==TIMER2_COMPARE_INTERRUPT_ENABLED
	TIMER2_INTERRUPT_COMPARE_ENABLE();
	GIE_ENABLE();
	#elif TIMER2_INTERRUPT_COMPARE_STATE==TIMER2_COMPARE_INTERRUPT_DISABLED
	TIMER2_INTERRUPT_COMPARE_DISABLE();
	#else
	ret=E_NOK;
	#endif
	
	#if TIMER2_INTERRUPT_OVERFLOW_STATE==TIMER2_OVERFLOW_INTERRUPT_ENABLED
	TIMER2_INTERRUPT_OVERFLOW_ENABLE();
	GIE_ENABLE();
	#elif TIMER2_INTERRUPT_OVERFLOW_STATE==TIMER2_OVERFLOW_INTERRUPT_DISABLED
	TIMER2_INTERRUPT_OVERFLOW_DISABLE();
	#else
	ret=E_NOK;
	#endif
	
	#else
	ret=E_NOK;
	#endif
	
	
	#elif TIMER2_WAVEFORM_MODE==TIMER2_WAVEFORM_MODE_CTC
	TIMER2_SELECT_WAVEFROM_MODE(TIMER2_WAVEFORM_MODE_CTC);
	#if TIMER2_VALIDATE_NON_PWM_COMPARE_MODE(TIMER2_COMPARE_MODE)
	TIMER2_SELECT_COMPARE_MODE(TIMER2_COMPARE_MODE);
	TIMER2_SELECT_CLOCK_SOURCE(TIMER2_CLOCK_SOURCE);
	
	#if TIMER2_INTERRUPT_COMPARE_STATE==TIMER2_COMPARE_INTERRUPT_ENABLED
	TIMER2_INTERRUPT_COMPARE_ENABLE();
	GIE_ENABLE();
	#elif TIMER2_INTERRUPT_COMPARE_STATE==TIMER2_COMPARE_INTERRUPT_DISABLED
	TIMER2_INTERRUPT_COMPARE_DISABLE();
	#else ret=E_NOK;
	#endif
	
	#if TIMER2_INTERRUPT_OVERFLOW_STATE==TIMER2_OVERFLOW_INTERRUPT_ENABLED
	TIMER2_INTERRUPT_OVERFLOW_ENABLE();
	GIE_ENABLE();
	#elif TIMER2_INTERRUPT_OVERFLOW_STATE==TIMER2_OVERFLOW_INTERRUPT_DISABLED
	TIMER2_INTERRUPT_OVERFLOW_DISABLE();
	#else
	ret=E_NOK;
	#endif
	
	#else
	ret=E_NOK;
	#endif
	
	#elif TIMER2_WAVEFORM_MODE==TIMER2_WAVEFORM_MODE_FAST_PWM
	
	#if TIMER2_VALIDATE_PWM_COMPARE_MODE(TIMER2_COMPARE_MODE)
	TIMER2_SELECT_WAVEFROM_MODE(TIMER2_WAVEFORM_MODE_FAST_PWM);
	TIMER2_SELECT_COMPARE_MODE(TIMER2_COMPARE_MODE);
	TIMER2_SELECT_CLOCK_SOURCE(TIMER2_CLOCK_SOURCE);
	
	#if TIMER2_INTERRUPT_COMPARE_STATE==TIMER2_COMPARE_INTERRUPT_ENABLED
	TIMER2_INTERRUPT_COMPARE_ENABLE();
	GIE_ENABLE();
	#elif TIMER2_INTERRUPT_COMPARE_STATE==TIMER2_COMPARE_INTERRUPT_DISABLED
	TIMER2_INTERRUPT_COMPARE_DISABLE();
	#else
	ret=E_NOK;
	#endif
	
	#if TIMER2_INTERRUPT_OVERFLOW_STATE==TIMER2_OVERFLOW_INTERRUPT_ENABLED
	TIMER2_INTERRUPT_OVERFLOW_ENABLE();
	GIE_ENABLE();
	#elif TIMER2_INTERRUPT_OVERFLOW_STATE==TIMER2_OVERFLOW_INTERRUPT_DISABLED
	TIMER2_INTERRUPT_OVERFLOW_DISABLE();
	#else
	ret=E_NOK;
	#endif
	
	#else
	ret=E_NOK;
	#endif
	
	#elif TIMER2_SELECT_WAVEFROM_MODE==TIMER2_WAVEFORM_MODE_PWM_PHASE_CORRECT
	
	#if TIMER2_VALIDATE_PWM_PHASE_CORRECT_COMPARE_MODE(TIMER2_COMPARE_MODE)
	TIMER2_SELECT_WAVEFROM_MODE(TIMER2_WAVEFORM_MODE_PWM_PHASE_CORRECT);
	TIMER2_SELECT_COMPARE_MODE(TIMER2_COMPARE_MODE);
	TIMER2_SELECT_CLOCK_SOURCE(TIMER2_CLOCK_SOURCE);
	
	#if TIMER2_INTERRUPT_COMPARE_STATE==TIMER2_COMPARE_INTERRUPT_ENABLED
	TIMER2_INTERRUPT_COMPARE_ENABLE();
	GIE_ENABLE();
	#elif TIMER2_INTERRUPT_COMPARE_STATE==TIMER2_COMPARE_INTERRUPT_DISABLED
	TIMER2_INTERRUPT_COMPARE_DISABLE();
	#else ret=E_NOK;
	#endif
	
	#if TIMER2_INTERRUPT_OVERFLOW_STATE==TIMER2_OVERFLOW_INTERRUPT_ENABLED
	TIMER2_INTERRUPT_OVERFLOW_ENABLE();
	GIE_ENABLE();
	#elif TIMER2_INTERRUPT_OVERFLOW_STATE==TIMER2_OVERFLOW_INTERRUPT_DISABLED
	TIMER2_INTERRUPT_OVERFLOW_DISABLE();
	#else
	ret=E_NOK;
	#endif
	
	#else
	ret=E_NOK;
	#endif
	
	#else
	ret=E_NOK;
	
	#endif
	#else
	ret=E_NOK
	#endif
	
	#elif TIMER2_STATE==TIMER2_DISABLED
	TIMER2_DISABLE();
	#endif
	/*TIMER2**/
	
	
	/*TIMER1*/
	
	
	
	
	/*TIMER1*/
	
	return ret;
}

STD_RETURN_TYPE TIMER2_disable()
{
	STD_RETURN_TYPE ret=E_OK;
	TIMER2_DISABLE();
	
	return ret;
}
STD_RETURN_TYPE TIMER2_send_overflow_isr(void (*ISR_ptr)(void))
{
	STD_RETURN_TYPE ret=E_OK;
	if(NULL==ISR_ptr)
	{
		ret=E_NOK;
	}
	else
	{
		TIMER2_overflow_ISR_ptr=ISR_ptr;
	}
	
	return ret;
}
STD_RETURN_TYPE TIMER2_send_compare_match_isr(void (*ISR_ptr)(void))
{
	STD_RETURN_TYPE ret=E_OK;
	if(NULL==ISR_ptr)
	{
		ret=E_NOK;
	}
	else
	{
		TIMER2_compare_ISR_ptr=ISR_ptr;
	}
	return ret;
}


STD_RETURN_TYPE TIMER2_set_compare_value(uint8 compare_value)
{
	STD_RETURN_TYPE ret=E_OK;
	TIMER2_WRITE_COMPARE_VALUE(compare_value);
	return ret;
}
STD_RETURN_TYPE TIMER2_write_value(uint8 value)
{
	STD_RETURN_TYPE ret=E_OK;
	TIMER2_WRITE_VALUE(value);
	return ret;
}
STD_RETURN_TYPE TIMER2_set_duty_cycle(uint8 duty_cycle)
{
	STD_RETURN_TYPE ret=E_OK;
	#if TIMER2_COMPARE_MODE==TIMER2_COMPARE_OUTPUT_PWM_CLEAR_ON_COMPARE_SET_ON_TOP
	TIMER2_WRITE_COMPARE_VALUE((uint8)(255*((float)duty_cycle/100.00)));
	#elif TIMER2_COMPARE_MODE==TIMER2_COMPARE_OUTPUT_PWM_SET_ON_COMPARE_CLEAR_ON_TOP
	TIMER2_WRITE_COMPARE_VALUE((uint8)((1-((float)duty_cycle/100.00))*255));
	#else
	ret=E_NOK;
	#endif 
	
	
	return ret;
}

__attribute__((signal)) void __vector_4(void)
{
	if(TIMER2_compare_ISR_ptr)
	{
		TIMER2_compare_ISR_ptr();
	}
	TIMER2_INTERRUPT_COMPARE_CLEAR_FLAG();
}

__attribute__((signal)) void __vector_5(void)
{
	if(TIMER2_overflow_ISR_ptr)
	{
		TIMER2_overflow_ISR_ptr();
	}
	TIMER2_INTERRUPT_OVERFLOW_CLEAR_FLAG();
}